[package]
name = "knipsa-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
knipsa = { path = "../crates/knipsa" }

[[bin]]
name = "geometry_inputs"
path = "fuzz_targets/geometry_inputs.rs"
test = false
doc = false

[[bin]]
name = "boolean_inputs"
path = "fuzz_targets/boolean_inputs.rs"
test = false
doc = false

[[bin]]
name = "double_boolean_inputs"
path = "fuzz_targets/double_boolean_inputs.rs"
test = false
doc = false

[workspace]
